### ISSUE TITLE
[Frontend] "Detached Operation Already Exists" Assertion Fails At Random

### ISSUE THREAD

**Issue by zzzDavid** [zzzDavid/hcl-dialect-prototype#68]
## Description
- `pytest` randomly aborts running `tests/mlir/test_schedule_streaming.py`
- 1 out of 10 runs of `python tests/mlir/test_schedule_streaming.py` would fail with assertion error:
```
llvm-project-14.0.0/mlir/lib/Bindings/Python/IRCore.cpp:955: static mlir::python::PyOperationRef mlir::python::PyOperation::createDetached(mlir::python::PyMlirContextRef, MlirOperation, pybind11::object): Assertion `liveOperations.count(operation.ptr) == 0 && "cannot create detached operation that already exists"' failed.
 #0 0x00007f22fbc9a05f PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
```

## Relevant Tests
Test cases in `tests/mlir/test_schedule_streaming.py`
Especially `test_move_outputs`

**Comment by chhzh123** [comment]
https://github.com/cornell-zhang/heterocl/commit/86f6ff366551314bdf8d1b6ba434f4bd1cf1a197
